#!/bin/zsh
# Type-checks everything outside Compose, and runs the HtmlHead tests.
#
# There is no test source set in this project and no JVM test dependency; this
# uses the kotlinc bundled with Android Studio and the jars Gradle has already
# downloaded. It catches what a device round trip is an expensive way to find.
#
#   tools/typecheck.sh          type-check only
#   tools/typecheck.sh --test   also compile and run tools/InstallerTest.kt
#
# Compose is out of reach here — MainActivity and ui/ need the Compose compiler
# plugin, so those are only checked by an Android Studio build.
set -e

ROOT=${0:a:h:h}
cd "$ROOT"

OUT=$(mktemp -d)
trap 'rm -rf "$OUT"' EXIT

KOTLIN_HOME="/Applications/Android Studio.app/Contents/plugins/Kotlin/kotlinc"
[[ -x "$KOTLIN_HOME/bin/kotlinc" ]] || {
    echo "kotlinc が見つかりません: $KOTLIN_HOME" >&2; exit 1
}

SDK=$(grep -i '^sdk.dir' local.properties 2>/dev/null | cut -d= -f2-)
ANDROID_JAR=$(ls -d "$SDK"/platforms/android-*/android.jar 2>/dev/null | sort -V | tail -1)
[[ -n "$ANDROID_JAR" ]] || {
    echo "android.jar が見つかりません。local.properties の sdk.dir を確認してください" >&2; exit 1
}

CACHE=~/.gradle/caches/modules-2/files-2.1
[[ -d "$CACHE" ]] || {
    echo "Gradle のキャッシュがありません。先に一度ビルドしてください" >&2; exit 1
}

# Newest of each artifact in the cache. Exact versions do not matter: this only
# needs the signatures to resolve, and an unresolved one fails loudly.
LIBS="$ANDROID_JAR"
add_jar() {
    local found=$(find "$CACHE" -name "$1" -not -name '*-sources.jar' 2>/dev/null | sort -V | tail -1)
    [[ -n "$found" ]] && LIBS="$LIBS:$found" || echo "  (見つからず、続行: $1)" >&2
}
add_aar() {
    local found=$(find "$CACHE" -name "$1" 2>/dev/null | sort -V | tail -1)
    [[ -n "$found" ]] || { echo "  (見つからず、続行: $1)" >&2; return; }
    local dir="$OUT/aar/${1:r}"
    mkdir -p "$dir"
    (cd "$dir" && unzip -oq "$found" classes.jar)
    LIBS="$LIBS:$dir/classes.jar"
}

add_jar 'room-common-*.jar'
add_jar 'kotlinx-coroutines-core-jvm-*.jar'
add_jar 'annotation-jvm-*.jar'
add_jar 'lifecycle-common-jvm-*.jar'
add_aar 'room-runtime-*.aar'
add_aar 'room-ktx-*.aar'
add_aar 'sqlite-2*.aar'
add_aar 'sqlite-framework-*.aar'
add_aar 'core-1*.aar'
add_aar 'core-ktx-*.aar'
add_aar 'activity-1*.aar'
add_aar 'documentfile-*.aar'
add_aar 'webkit-*.aar'
add_aar 'versionedparcelable-1.1.1.aar'

# R is generated by the build, and WebAppActivity drags in the whole Compose
# graph. Neither is under test here, so both are stood in for by their shape.
python3 - "$OUT" <<'PY'
import os, sys, xml.etree.ElementTree as ET
out = sys.argv[1]
names = set()
for root, _, files in os.walk("app/src/main/res"):
    for f in files:
        if not f.endswith(".xml"):
            continue
        try:
            tree = ET.parse(os.path.join(root, f)).getroot()
        except Exception:
            continue
        names.update(el.get("name") for el in tree if el.tag == "string" and el.get("name"))
body = "\n".join(f"        const val {n} = {i + 1}" for i, n in enumerate(sorted(names)))
open(os.path.join(out, "Stubs.kt"), "w").write(
    "package com.example.pwalibrary\n\n"
    "object R {\n    object string {\n" + body + "\n    }\n}\n"
)
open(os.path.join(out, "WebAppActivityStub.kt"), "w").write(
    "package com.example.pwalibrary.web\n\n"
    "import android.content.Context\n"
    "import android.content.Intent\n\n"
    "object WebAppActivity {\n"
    "    fun intentFor(context: Context, uuid: String): Intent = Intent()\n"
    "}\n"
)
PY

SRC=app/src/main/java/com/example/pwalibrary
SOURCES=(
    "$OUT/Stubs.kt" "$OUT/WebAppActivityStub.kt"
    $SRC/install/*.kt $SRC/data/*.kt $SRC/files/*.kt $SRC/shortcut/*.kt
    $SRC/web/AppAssetRegistry.kt $SRC/web/ShimPathHandler.kt $SRC/web/LocalFilePathHandler.kt
)

echo "型チェック: install / data / files / shortcut / web（Compose を除く）"
"$KOTLIN_HOME/bin/kotlinc" -cp "$LIBS" -d "$OUT/classes" -nowarn $SOURCES 2>&1 | grep -v '^warning:' || true
[[ -d "$OUT/classes/com/example/pwalibrary/data" ]] || { echo "型チェック 失敗"; exit 1; }
echo "型チェック OK"

[[ "$1" == "--test" ]] || exit 0

echo
echo "インストーラの純粋な部分のテスト（HtmlHead / InstallPaths）"
"$KOTLIN_HOME/bin/kotlinc" -d "$OUT/test" -nowarn \
    "$SRC/install/HtmlHead.kt" "$SRC/install/InstallPaths.kt" tools/InstallerTest.kt \
    2>&1 | grep -v '^warning:' || true
java -cp "$OUT/test:$KOTLIN_HOME/lib/kotlin-stdlib.jar" InstallerTestKt
